"""empty message

Revision ID: 7f9406f5630d
Revises: 
Create Date: 2019-01-11 21:08:23.143893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9406f5630d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redtree_event_id', sa.Integer(), nullable=True),
    sa.Column('event_status', sa.String(length=80), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('targets', sa.Text(), nullable=True),
    sa.Column('scan_name', sa.String(length=80), nullable=True),
    sa.Column('scan_type', sa.String(length=80), nullable=True),
    sa.Column('nessus_url', sa.String(length=80), nullable=True),
    sa.Column('nessus_username', sa.String(length=80), nullable=True),
    sa.Column('nessus_password', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('scan_message', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('process_started', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('scan_event_history', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_events')
    op.drop_table('scan')
    op.drop_table('events')
    # ### end Alembic commands ###
